spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: flyway
